# Generated by Django 3.2.8 on 2021-10-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_score', models.IntegerField()),
                ('role_title', models.CharField(max_length=200)),
                ('role_description', models.CharField(max_length=400)),
                ('role_type', models.CharField(max_length=200)),
                ('role_alignment', models.CharField(max_length=200)),
            ],
        ),
    ]
