# Generated by Django 3.2.8 on 2021-10-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfapp', '0003_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_score', models.IntegerField()),
                ('role_title', models.CharField(max_length=200)),
                ('player_name', models.CharField(max_length=200)),
                ('role_alignment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WolfNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
