# Generated by Django 3.2.8 on 2021-11-01 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wolfapp', '0004_roleassignment_wolfnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggle', models.BooleanField(default=True)),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='wolfapp.role')),
            ],
        ),
    ]
