# Generated by Django 3.2.8 on 2021-11-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfapp', '0009_alter_role_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
