# Generated by Django 3.2.8 on 2021-11-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wolfapp', '0010_roleassignment_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='game_score',
            new_name='role_score',
        ),
    ]
